name: Validate

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
      with:
        egress-policy: audit

    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Install uv
      uses: astral-sh/setup-uv@2ddd2b9cb38ad8efd50337e8ab201519a34c9f24 # v7.1.1
      with:
        version: "latest"

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Install all dependencies
      run: |
        uv sync --all-packages

    - name: Check formatting with ruff format
      run: |
        uv run ruff format --target-version py310 --check vexipy tests

    - name: Lint with ruff check
      run: |
        uv run ruff check --show-fixes

    - name: Check import sorting with isort
      run: |
        uv run isort --check-only vexipy tests

    - name: Type check with mypy
      run: |
        uv run mypy vexipy

    - name: Test with pytest
      run: |
        uv run pytest --cov=vexipy --cov-branch --cov-report=xml

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
      if: matrix.python-version == '3.11'
      with:
        token: ${{ secrets.CODECOV_TOKEN }}